version: '3'
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: imersao17
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data